#ifndef DLLMYSQLDLL_GLOBAL_H
#define DLLMYSQLDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DLLMYSQLDLL_LIBRARY)
#  define DLLMYSQLDLLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DLLMYSQLDLLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DLLMYSQLDLL_GLOBAL_H
