/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.10.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLCDNumber>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QStackedWidget *stackedWidget;
    QWidget *page_1;
    QLabel *label_2;
    QLabel *label;
    QWidget *page_2;
    QLabel *label_4;
    QWidget *page_3;
    QLabel *label_5;
    QPushButton *NostaRahaa;
    QPushButton *NaytaSaldo;
    QPushButton *SelaaTili;
    QPushButton *KirjauduUlos;
    QWidget *page_4;
    QLabel *label_6;
    QPushButton *Nosto20e;
    QPushButton *Nosto40e;
    QPushButton *Nosto60e;
    QPushButton *Nosto100e;
    QPushButton *Nosto200e;
    QPushButton *Nosto500e;
    QPushButton *Peruuta;
    QWidget *page_5;
    QLabel *label_7;
    QPushButton *Jatka;
    QWidget *page_6;
    QLabel *label_8;
    QLabel *label_9;
    QPushButton *Sulje;
    QPushButton *SeuraavaSivu;
    QWidget *page_7;
    QLabel *label_11;
    QLabel *label_12;
    QPushButton *Sulje_2;
    QWidget *page_9;
    QLabel *label_10;
    QLabel *banksimul;
    QToolButton *KirjauduUlos_2;
    QToolButton *Paavalikko;
    QLCDNumber *lcdNumber;
    QToolButton *KirjauduSisaan;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(1080, 1920);
        QFont font;
        font.setFamily(QStringLiteral("Ebrima"));
        MainWindow->setFont(font);
        MainWindow->setStyleSheet(QStringLiteral("background-color: rgb(60, 60, 60);"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        stackedWidget = new QStackedWidget(centralWidget);
        stackedWidget->setObjectName(QStringLiteral("stackedWidget"));
        stackedWidget->setGeometry(QRect(-10, 50, 1080, 1920));
        QFont font1;
        font1.setPointSize(9);
        stackedWidget->setFont(font1);
        stackedWidget->setFocusPolicy(Qt::ClickFocus);
        stackedWidget->setContextMenuPolicy(Qt::DefaultContextMenu);
        stackedWidget->setStyleSheet(QStringLiteral("background-color: rgb(60, 60, 60);"));
        stackedWidget->setLineWidth(15);
        page_1 = new QWidget();
        page_1->setObjectName(QStringLiteral("page_1"));
        label_2 = new QLabel(page_1);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 460, 1081, 271));
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Maximum);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(label_2->sizePolicy().hasHeightForWidth());
        label_2->setSizePolicy(sizePolicy);
        QPalette palette;
        QBrush brush(QColor(255, 85, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(60, 60, 60, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        QBrush brush2(QColor(255, 255, 255, 127));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_2->setPalette(palette);
        QFont font2;
        font2.setPointSize(47);
        label_2->setFont(font2);
        label = new QLabel(page_1);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(-40, -20, 1161, 171));
        QSizePolicy sizePolicy1(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(label->sizePolicy().hasHeightForWidth());
        label->setSizePolicy(sizePolicy1);
        QPalette palette1;
        QBrush brush3(QColor(58, 95, 231, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label->setPalette(palette1);
        QFont font3;
        font3.setPointSize(67);
        font3.setBold(false);
        font3.setItalic(false);
        font3.setUnderline(false);
        font3.setWeight(50);
        font3.setStyleStrategy(QFont::PreferDefault);
        label->setFont(font3);
        label->setCursor(QCursor(Qt::ArrowCursor));
        label->setMouseTracking(true);
        label->setFrameShape(QFrame::Box);
        label->setLineWidth(12);
        label->setAlignment(Qt::AlignCenter);
        label->setWordWrap(false);
        stackedWidget->addWidget(page_1);
        page_2 = new QWidget();
        page_2->setObjectName(QStringLiteral("page_2"));
        label_4 = new QLabel(page_2);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(0, 460, 1080, 361));
        sizePolicy.setHeightForWidth(label_4->sizePolicy().hasHeightForWidth());
        label_4->setSizePolicy(sizePolicy);
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_4->setPalette(palette2);
        label_4->setFont(font2);
        stackedWidget->addWidget(page_2);
        page_3 = new QWidget();
        page_3->setObjectName(QStringLiteral("page_3"));
        label_5 = new QLabel(page_3);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(-10, 460, 1080, 271));
        sizePolicy.setHeightForWidth(label_5->sizePolicy().hasHeightForWidth());
        label_5->setSizePolicy(sizePolicy);
        QPalette palette3;
        QBrush brush4(QColor(255, 93, 0, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush4);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush4);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_5->setPalette(palette3);
        QFont font4;
        font4.setFamily(QStringLiteral("MS UI Gothic"));
        font4.setPointSize(40);
        label_5->setFont(font4);
        NostaRahaa = new QPushButton(page_3);
        NostaRahaa->setObjectName(QStringLiteral("NostaRahaa"));
        NostaRahaa->setGeometry(QRect(30, 690, 491, 281));
        QPalette palette4;
        QBrush brush5(QColor(231, 231, 231, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        QBrush brush6(QColor(33, 0, 100, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush6);
        QBrush brush7(QColor(255, 255, 255, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush7);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush7);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush7);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush7);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush7);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush7);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        NostaRahaa->setPalette(palette4);
        QFont font5;
        font5.setFamily(QStringLiteral("Ebrima"));
        font5.setPointSize(36);
        font5.setBold(false);
        font5.setItalic(false);
        font5.setWeight(50);
        NostaRahaa->setFont(font5);
        NostaRahaa->setMouseTracking(false);
        NostaRahaa->setStyleSheet(QLatin1String("background-color: rgb(33, 0, 100);\n"
"font: 36pt \"Ebrima\"; "));
        NaytaSaldo = new QPushButton(page_3);
        NaytaSaldo->setObjectName(QStringLiteral("NaytaSaldo"));
        NaytaSaldo->setGeometry(QRect(560, 690, 491, 281));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush7);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush7);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush7);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush7);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush7);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush7);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        NaytaSaldo->setPalette(palette5);
        NaytaSaldo->setMouseTracking(true);
        NaytaSaldo->setStyleSheet(QLatin1String("background-color: rgb(33, 0, 100);\n"
"font: 36pt \"Ebrima\"; "));
        SelaaTili = new QPushButton(page_3);
        SelaaTili->setObjectName(QStringLiteral("SelaaTili"));
        SelaaTili->setGeometry(QRect(30, 1010, 491, 281));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette6.setBrush(QPalette::Active, QPalette::Dark, brush7);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush6);
        QBrush brush8(QColor(255, 255, 255, 102));
        brush8.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Highlight, brush8);
        palette6.setBrush(QPalette::Active, QPalette::NoRole, brush7);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::Dark, brush7);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::Highlight, brush8);
        palette6.setBrush(QPalette::Inactive, QPalette::NoRole, brush7);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush7);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::Dark, brush7);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush7);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush7);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        QBrush brush9(QColor(0, 0, 0, 102));
        brush9.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Disabled, QPalette::Highlight, brush9);
        palette6.setBrush(QPalette::Disabled, QPalette::NoRole, brush7);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        SelaaTili->setPalette(palette6);
        SelaaTili->setStyleSheet(QLatin1String("background-color: rgb(33, 0, 100);\n"
"font: 36pt \"Ebrima\"; "));
        KirjauduUlos = new QPushButton(page_3);
        KirjauduUlos->setObjectName(QStringLiteral("KirjauduUlos"));
        KirjauduUlos->setGeometry(QRect(560, 1010, 491, 281));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette7.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette7.setBrush(QPalette::Active, QPalette::Dark, brush7);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette7.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::Dark, brush7);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette7.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush7);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::Dark, brush7);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush7);
        palette7.setBrush(QPalette::Disabled, QPalette::ButtonText, brush7);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        KirjauduUlos->setPalette(palette7);
        KirjauduUlos->setStyleSheet(QLatin1String("background-color: rgb(33, 0, 100);\n"
"font: 36pt \"Ebrima\"; "));
        stackedWidget->addWidget(page_3);
        page_4 = new QWidget();
        page_4->setObjectName(QStringLiteral("page_4"));
        label_6 = new QLabel(page_4);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(0, 460, 1080, 271));
        sizePolicy.setHeightForWidth(label_6->sizePolicy().hasHeightForWidth());
        label_6->setSizePolicy(sizePolicy);
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette8.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette8.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette8.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_6->setPalette(palette8);
        label_6->setFont(font2);
        Nosto20e = new QPushButton(page_4);
        Nosto20e->setObjectName(QStringLiteral("Nosto20e"));
        Nosto20e->setGeometry(QRect(30, 690, 491, 281));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette9.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette9.setBrush(QPalette::Active, QPalette::Dark, brush7);
        palette9.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette9.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette9.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette9.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette9.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette9.setBrush(QPalette::Inactive, QPalette::Dark, brush7);
        palette9.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette9.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette9.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette9.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush7);
        palette9.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette9.setBrush(QPalette::Disabled, QPalette::Dark, brush7);
        palette9.setBrush(QPalette::Disabled, QPalette::Text, brush7);
        palette9.setBrush(QPalette::Disabled, QPalette::ButtonText, brush7);
        palette9.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette9.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        Nosto20e->setPalette(palette9);
        Nosto20e->setStyleSheet(QLatin1String("background-color: rgb(33, 0, 100);\n"
"font: 36pt \"Ebrima\"; "));
        Nosto40e = new QPushButton(page_4);
        Nosto40e->setObjectName(QStringLiteral("Nosto40e"));
        Nosto40e->setGeometry(QRect(560, 690, 491, 281));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette10.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette10.setBrush(QPalette::Active, QPalette::Dark, brush7);
        palette10.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette10.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette10.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette10.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette10.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette10.setBrush(QPalette::Inactive, QPalette::Dark, brush7);
        palette10.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette10.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette10.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette10.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush7);
        palette10.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette10.setBrush(QPalette::Disabled, QPalette::Dark, brush7);
        palette10.setBrush(QPalette::Disabled, QPalette::Text, brush7);
        palette10.setBrush(QPalette::Disabled, QPalette::ButtonText, brush7);
        palette10.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette10.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        Nosto40e->setPalette(palette10);
        Nosto40e->setStyleSheet(QLatin1String("background-color: rgb(33, 0, 100);\n"
"font: 36pt \"Ebrima\"; "));
        Nosto60e = new QPushButton(page_4);
        Nosto60e->setObjectName(QStringLiteral("Nosto60e"));
        Nosto60e->setGeometry(QRect(30, 1010, 491, 281));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette11.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette11.setBrush(QPalette::Active, QPalette::Dark, brush7);
        palette11.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette11.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette11.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette11.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette11.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette11.setBrush(QPalette::Inactive, QPalette::Dark, brush7);
        palette11.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette11.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette11.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette11.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush7);
        palette11.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette11.setBrush(QPalette::Disabled, QPalette::Dark, brush7);
        palette11.setBrush(QPalette::Disabled, QPalette::Text, brush7);
        palette11.setBrush(QPalette::Disabled, QPalette::ButtonText, brush7);
        palette11.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette11.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        Nosto60e->setPalette(palette11);
        Nosto60e->setStyleSheet(QLatin1String("background-color: rgb(33, 0, 100);\n"
"font: 36pt \"Ebrima\"; "));
        Nosto100e = new QPushButton(page_4);
        Nosto100e->setObjectName(QStringLiteral("Nosto100e"));
        Nosto100e->setGeometry(QRect(560, 1010, 491, 281));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette12.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette12.setBrush(QPalette::Active, QPalette::Dark, brush7);
        palette12.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette12.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette12.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette12.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette12.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette12.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette12.setBrush(QPalette::Inactive, QPalette::Dark, brush7);
        palette12.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette12.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette12.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette12.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette12.setBrush(QPalette::Disabled, QPalette::WindowText, brush7);
        palette12.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette12.setBrush(QPalette::Disabled, QPalette::Dark, brush7);
        palette12.setBrush(QPalette::Disabled, QPalette::Text, brush7);
        palette12.setBrush(QPalette::Disabled, QPalette::ButtonText, brush7);
        palette12.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette12.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        Nosto100e->setPalette(palette12);
        Nosto100e->setStyleSheet(QLatin1String("background-color: rgb(33, 0, 100);\n"
"font: 36pt \"Ebrima\"; "));
        Nosto200e = new QPushButton(page_4);
        Nosto200e->setObjectName(QStringLiteral("Nosto200e"));
        Nosto200e->setGeometry(QRect(30, 1330, 491, 281));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette13.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette13.setBrush(QPalette::Active, QPalette::Dark, brush7);
        palette13.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette13.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette13.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette13.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette13.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette13.setBrush(QPalette::Inactive, QPalette::Dark, brush7);
        palette13.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette13.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette13.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette13.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush7);
        palette13.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette13.setBrush(QPalette::Disabled, QPalette::Dark, brush7);
        palette13.setBrush(QPalette::Disabled, QPalette::Text, brush7);
        palette13.setBrush(QPalette::Disabled, QPalette::ButtonText, brush7);
        palette13.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette13.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        Nosto200e->setPalette(palette13);
        Nosto200e->setStyleSheet(QLatin1String("background-color: rgb(33, 0, 100);\n"
"font: 36pt \"Ebrima\"; "));
        Nosto500e = new QPushButton(page_4);
        Nosto500e->setObjectName(QStringLiteral("Nosto500e"));
        Nosto500e->setGeometry(QRect(560, 1330, 491, 281));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette14.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette14.setBrush(QPalette::Active, QPalette::Dark, brush7);
        palette14.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette14.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette14.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette14.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette14.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette14.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette14.setBrush(QPalette::Inactive, QPalette::Dark, brush7);
        palette14.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette14.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette14.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette14.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette14.setBrush(QPalette::Disabled, QPalette::WindowText, brush7);
        palette14.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette14.setBrush(QPalette::Disabled, QPalette::Dark, brush7);
        palette14.setBrush(QPalette::Disabled, QPalette::Text, brush7);
        palette14.setBrush(QPalette::Disabled, QPalette::ButtonText, brush7);
        palette14.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette14.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        Nosto500e->setPalette(palette14);
        Nosto500e->setStyleSheet(QLatin1String("background-color: rgb(33, 0, 100);\n"
"font: 36pt \"Ebrima\"; "));
        Peruuta = new QPushButton(page_4);
        Peruuta->setObjectName(QStringLiteral("Peruuta"));
        Peruuta->setGeometry(QRect(30, 1650, 1021, 171));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette15.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette15.setBrush(QPalette::Active, QPalette::Dark, brush7);
        palette15.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette15.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette15.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette15.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette15.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette15.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette15.setBrush(QPalette::Inactive, QPalette::Dark, brush7);
        palette15.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette15.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette15.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette15.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette15.setBrush(QPalette::Disabled, QPalette::WindowText, brush7);
        palette15.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette15.setBrush(QPalette::Disabled, QPalette::Dark, brush7);
        palette15.setBrush(QPalette::Disabled, QPalette::Text, brush7);
        palette15.setBrush(QPalette::Disabled, QPalette::ButtonText, brush7);
        palette15.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette15.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        Peruuta->setPalette(palette15);
        Peruuta->setStyleSheet(QLatin1String("background-color: rgb(33, 0, 100);\n"
"font: 36pt \"Ebrima\"; "));
        stackedWidget->addWidget(page_4);
        page_5 = new QWidget();
        page_5->setObjectName(QStringLiteral("page_5"));
        label_7 = new QLabel(page_5);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(0, 460, 1080, 271));
        sizePolicy.setHeightForWidth(label_7->sizePolicy().hasHeightForWidth());
        label_7->setSizePolicy(sizePolicy);
        QPalette palette16;
        palette16.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette16.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette16.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette16.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette16.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette16.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette16.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette16.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette16.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette16.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette16.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_7->setPalette(palette16);
        label_7->setFont(font2);
        Jatka = new QPushButton(page_5);
        Jatka->setObjectName(QStringLiteral("Jatka"));
        Jatka->setGeometry(QRect(300, 1010, 491, 281));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette17.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette17.setBrush(QPalette::Active, QPalette::Dark, brush7);
        palette17.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette17.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette17.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette17.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette17.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette17.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette17.setBrush(QPalette::Inactive, QPalette::Dark, brush7);
        palette17.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette17.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette17.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette17.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette17.setBrush(QPalette::Disabled, QPalette::WindowText, brush7);
        palette17.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette17.setBrush(QPalette::Disabled, QPalette::Dark, brush7);
        palette17.setBrush(QPalette::Disabled, QPalette::Text, brush7);
        palette17.setBrush(QPalette::Disabled, QPalette::ButtonText, brush7);
        palette17.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette17.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        Jatka->setPalette(palette17);
        Jatka->setStyleSheet(QLatin1String("background-color: rgb(33, 0, 100);\n"
"font: 36pt \"Ebrima\"; "));
        stackedWidget->addWidget(page_5);
        page_6 = new QWidget();
        page_6->setObjectName(QStringLiteral("page_6"));
        label_8 = new QLabel(page_6);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(0, 360, 1080, 271));
        sizePolicy.setHeightForWidth(label_8->sizePolicy().hasHeightForWidth());
        label_8->setSizePolicy(sizePolicy);
        QPalette palette18;
        palette18.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette18.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette18.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette18.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette18.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette18.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette18.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette18.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette18.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette18.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette18.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_8->setPalette(palette18);
        label_8->setFont(font2);
        label_9 = new QLabel(page_6);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(20, 560, 481, 921));
        sizePolicy.setHeightForWidth(label_9->sizePolicy().hasHeightForWidth());
        label_9->setSizePolicy(sizePolicy);
        QPalette palette19;
        QBrush brush10(QColor(62, 91, 255, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette19.setBrush(QPalette::Active, QPalette::WindowText, brush10);
        palette19.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette19.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette19.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette19.setBrush(QPalette::Inactive, QPalette::WindowText, brush10);
        palette19.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette19.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette19.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette19.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette19.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette19.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette19.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_9->setPalette(palette19);
        label_9->setFont(font2);
        Sulje = new QPushButton(page_6);
        Sulje->setObjectName(QStringLiteral("Sulje"));
        Sulje->setGeometry(QRect(30, 1480, 491, 281));
        QPalette palette20;
        palette20.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette20.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette20.setBrush(QPalette::Active, QPalette::Dark, brush7);
        palette20.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette20.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette20.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette20.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette20.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette20.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette20.setBrush(QPalette::Inactive, QPalette::Dark, brush7);
        palette20.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette20.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette20.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette20.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette20.setBrush(QPalette::Disabled, QPalette::WindowText, brush7);
        palette20.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette20.setBrush(QPalette::Disabled, QPalette::Dark, brush7);
        palette20.setBrush(QPalette::Disabled, QPalette::Text, brush7);
        palette20.setBrush(QPalette::Disabled, QPalette::ButtonText, brush7);
        palette20.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette20.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        Sulje->setPalette(palette20);
        Sulje->setStyleSheet(QLatin1String("background-color: rgb(33, 0, 100);\n"
"font: 36pt \"Ebrima\"; "));
        SeuraavaSivu = new QPushButton(page_6);
        SeuraavaSivu->setObjectName(QStringLiteral("SeuraavaSivu"));
        SeuraavaSivu->setGeometry(QRect(540, 1480, 491, 281));
        QPalette palette21;
        palette21.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette21.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette21.setBrush(QPalette::Active, QPalette::Dark, brush7);
        palette21.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette21.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette21.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette21.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette21.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette21.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette21.setBrush(QPalette::Inactive, QPalette::Dark, brush7);
        palette21.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette21.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette21.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette21.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette21.setBrush(QPalette::Disabled, QPalette::WindowText, brush7);
        palette21.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette21.setBrush(QPalette::Disabled, QPalette::Dark, brush7);
        palette21.setBrush(QPalette::Disabled, QPalette::Text, brush7);
        palette21.setBrush(QPalette::Disabled, QPalette::ButtonText, brush7);
        palette21.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette21.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        SeuraavaSivu->setPalette(palette21);
        SeuraavaSivu->setStyleSheet(QLatin1String("background-color: rgb(33, 0, 100);\n"
"font: 36pt \"Ebrima\"; "));
        stackedWidget->addWidget(page_6);
        page_7 = new QWidget();
        page_7->setObjectName(QStringLiteral("page_7"));
        label_11 = new QLabel(page_7);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(0, 460, 1080, 271));
        sizePolicy.setHeightForWidth(label_11->sizePolicy().hasHeightForWidth());
        label_11->setSizePolicy(sizePolicy);
        QPalette palette22;
        palette22.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette22.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette22.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette22.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette22.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette22.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette22.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette22.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette22.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette22.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette22.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette22.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_11->setPalette(palette22);
        label_11->setFont(font2);
        label_12 = new QLabel(page_7);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(330, 680, 441, 551));
        sizePolicy.setHeightForWidth(label_12->sizePolicy().hasHeightForWidth());
        label_12->setSizePolicy(sizePolicy);
        QPalette palette23;
        palette23.setBrush(QPalette::Active, QPalette::WindowText, brush10);
        palette23.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette23.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette23.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette23.setBrush(QPalette::Inactive, QPalette::WindowText, brush10);
        palette23.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette23.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette23.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette23.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette23.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette23.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette23.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_12->setPalette(palette23);
        label_12->setFont(font2);
        Sulje_2 = new QPushButton(page_7);
        Sulje_2->setObjectName(QStringLiteral("Sulje_2"));
        Sulje_2->setGeometry(QRect(300, 1480, 491, 281));
        QPalette palette24;
        palette24.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette24.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette24.setBrush(QPalette::Active, QPalette::Dark, brush7);
        palette24.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette24.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette24.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette24.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette24.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette24.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette24.setBrush(QPalette::Inactive, QPalette::Dark, brush7);
        palette24.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette24.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette24.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette24.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette24.setBrush(QPalette::Disabled, QPalette::WindowText, brush7);
        palette24.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette24.setBrush(QPalette::Disabled, QPalette::Dark, brush7);
        palette24.setBrush(QPalette::Disabled, QPalette::Text, brush7);
        palette24.setBrush(QPalette::Disabled, QPalette::ButtonText, brush7);
        palette24.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette24.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        Sulje_2->setPalette(palette24);
        Sulje_2->setStyleSheet(QLatin1String("background-color: rgb(33, 0, 100);\n"
"font: 36pt \"Ebrima\"; "));
        stackedWidget->addWidget(page_7);
        page_9 = new QWidget();
        page_9->setObjectName(QStringLiteral("page_9"));
        label_10 = new QLabel(page_9);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(10, 460, 1080, 271));
        sizePolicy.setHeightForWidth(label_10->sizePolicy().hasHeightForWidth());
        label_10->setSizePolicy(sizePolicy);
        QPalette palette25;
        palette25.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette25.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette25.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette25.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette25.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette25.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette25.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette25.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette25.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette25.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette25.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette25.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        label_10->setPalette(palette25);
        label_10->setFont(font2);
        stackedWidget->addWidget(page_9);
        banksimul = new QLabel(centralWidget);
        banksimul->setObjectName(QStringLiteral("banksimul"));
        banksimul->setGeometry(QRect(20, 0, 221, 61));
        QFont font6;
        font6.setFamily(QStringLiteral("Freestyle Script"));
        font6.setPointSize(19);
        banksimul->setFont(font6);
        KirjauduUlos_2 = new QToolButton(centralWidget);
        KirjauduUlos_2->setObjectName(QStringLiteral("KirjauduUlos_2"));
        KirjauduUlos_2->setGeometry(QRect(900, 10, 171, 51));
        QSizePolicy sizePolicy2(QSizePolicy::Maximum, QSizePolicy::Fixed);
        sizePolicy2.setHorizontalStretch(0);
        sizePolicy2.setVerticalStretch(0);
        sizePolicy2.setHeightForWidth(KirjauduUlos_2->sizePolicy().hasHeightForWidth());
        KirjauduUlos_2->setSizePolicy(sizePolicy2);
        QPalette palette26;
        palette26.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette26.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette26.setBrush(QPalette::Active, QPalette::Dark, brush7);
        palette26.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette26.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette26.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette26.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette26.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette26.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette26.setBrush(QPalette::Inactive, QPalette::Dark, brush7);
        palette26.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette26.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette26.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette26.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette26.setBrush(QPalette::Disabled, QPalette::WindowText, brush7);
        palette26.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette26.setBrush(QPalette::Disabled, QPalette::Dark, brush7);
        palette26.setBrush(QPalette::Disabled, QPalette::Text, brush7);
        palette26.setBrush(QPalette::Disabled, QPalette::ButtonText, brush7);
        palette26.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette26.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        KirjauduUlos_2->setPalette(palette26);
        QFont font7;
        font7.setFamily(QStringLiteral("Ebrima"));
        font7.setPointSize(12);
        font7.setBold(false);
        font7.setItalic(false);
        font7.setWeight(50);
        KirjauduUlos_2->setFont(font7);
        KirjauduUlos_2->setStyleSheet(QLatin1String("background-color: rgb(33, 0, 100);\n"
"font: 12pt \"Ebrima\"; "));
        Paavalikko = new QToolButton(centralWidget);
        Paavalikko->setObjectName(QStringLiteral("Paavalikko"));
        Paavalikko->setGeometry(QRect(540, 10, 171, 51));
        QPalette palette27;
        palette27.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette27.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette27.setBrush(QPalette::Active, QPalette::Dark, brush7);
        palette27.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette27.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette27.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette27.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette27.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette27.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette27.setBrush(QPalette::Inactive, QPalette::Dark, brush7);
        palette27.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette27.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette27.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette27.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette27.setBrush(QPalette::Disabled, QPalette::WindowText, brush7);
        palette27.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette27.setBrush(QPalette::Disabled, QPalette::Dark, brush7);
        palette27.setBrush(QPalette::Disabled, QPalette::Text, brush7);
        palette27.setBrush(QPalette::Disabled, QPalette::ButtonText, brush7);
        palette27.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette27.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        Paavalikko->setPalette(palette27);
        Paavalikko->setFont(font7);
        Paavalikko->setStyleSheet(QLatin1String("background-color: rgb(33, 0, 100);\n"
"font: 12pt \"Ebrima\"; "));
        lcdNumber = new QLCDNumber(centralWidget);
        lcdNumber->setObjectName(QStringLiteral("lcdNumber"));
        lcdNumber->setGeometry(QRect(450, 10, 81, 51));
        QPalette palette28;
        palette28.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette28.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush11(QColor(8, 35, 5, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette28.setBrush(QPalette::Active, QPalette::Dark, brush11);
        palette28.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette28.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette28.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette28.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette28.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette28.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette28.setBrush(QPalette::Inactive, QPalette::Dark, brush11);
        palette28.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette28.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette28.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette28.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette28.setBrush(QPalette::Disabled, QPalette::WindowText, brush11);
        palette28.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette28.setBrush(QPalette::Disabled, QPalette::Dark, brush11);
        palette28.setBrush(QPalette::Disabled, QPalette::Text, brush11);
        palette28.setBrush(QPalette::Disabled, QPalette::ButtonText, brush11);
        palette28.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette28.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        lcdNumber->setPalette(palette28);
        KirjauduSisaan = new QToolButton(centralWidget);
        KirjauduSisaan->setObjectName(QStringLiteral("KirjauduSisaan"));
        KirjauduSisaan->setGeometry(QRect(720, 10, 171, 51));
        QPalette palette29;
        palette29.setBrush(QPalette::Active, QPalette::WindowText, brush5);
        palette29.setBrush(QPalette::Active, QPalette::Button, brush6);
        palette29.setBrush(QPalette::Active, QPalette::Dark, brush7);
        palette29.setBrush(QPalette::Active, QPalette::Text, brush5);
        palette29.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        palette29.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette29.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette29.setBrush(QPalette::Inactive, QPalette::WindowText, brush5);
        palette29.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette29.setBrush(QPalette::Inactive, QPalette::Dark, brush7);
        palette29.setBrush(QPalette::Inactive, QPalette::Text, brush5);
        palette29.setBrush(QPalette::Inactive, QPalette::ButtonText, brush5);
        palette29.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette29.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette29.setBrush(QPalette::Disabled, QPalette::WindowText, brush7);
        palette29.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette29.setBrush(QPalette::Disabled, QPalette::Dark, brush7);
        palette29.setBrush(QPalette::Disabled, QPalette::Text, brush7);
        palette29.setBrush(QPalette::Disabled, QPalette::ButtonText, brush7);
        palette29.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette29.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        KirjauduSisaan->setPalette(palette29);
        KirjauduSisaan->setFont(font7);
        KirjauduSisaan->setStyleSheet(QLatin1String("background-color: rgb(33, 0, 100);\n"
"font: 12pt \"Ebrima\"; "));
        MainWindow->setCentralWidget(centralWidget);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        stackedWidget->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        label_2->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:47pt;\">Tervetuloa pankkiautomaatille! </span></p><p align=\"center\"><span style=\" font-size:47pt;\">Ole hyv\303\244 ja sy\303\266t\303\244 kortti.</span></p></body></html>", nullptr));
        label->setText(QApplication::translate("MainWindow", "<html><head/><body><p>PANKKIAUTOMAATTI</p></body></html>", nullptr));
        label_4->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt;\">Sy\303\266tit tunnusluvun </span></p><p align=\"center\"><span style=\" font-size:48pt;\">kolme kertaa v\303\244\303\244rin.</span></p><p align=\"center\"><span style=\" font-size:48pt;\">Korttisi on lukittu!</span></p><p align=\"center\"><span style=\" font-size:48pt;\">Ota yhteys pankkiin!</span></p></body></html>", nullptr));
        label_5->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:65pt;\">Valitse toiminto</span></p></body></html>", nullptr));
#ifndef QT_NO_TOOLTIP
        NostaRahaa->setToolTip(QString());
#endif // QT_NO_TOOLTIP
#ifndef QT_NO_WHATSTHIS
        NostaRahaa->setWhatsThis(QApplication::translate("MainWindow", "font-color: white;", nullptr));
#endif // QT_NO_WHATSTHIS
        NostaRahaa->setText(QApplication::translate("MainWindow", "NOSTA RAHAA", nullptr));
        NaytaSaldo->setText(QApplication::translate("MainWindow", "N\303\204YT\303\204 SALDO", nullptr));
#ifndef QT_NO_TOOLTIP
        SelaaTili->setToolTip(QString());
#endif // QT_NO_TOOLTIP
#ifndef QT_NO_WHATSTHIS
        SelaaTili->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        SelaaTili->setText(QApplication::translate("MainWindow", "SELAA\n"
" TILITAPAHTUMIA", nullptr));
        KirjauduUlos->setText(QApplication::translate("MainWindow", "KIRJAUDU ULOS", nullptr));
        label_6->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt;\">Valitse nostettava summa</span></p></body></html>", nullptr));
        Nosto20e->setText(QApplication::translate("MainWindow", "20 \342\202\254", nullptr));
        Nosto40e->setText(QApplication::translate("MainWindow", "40 \342\202\254", nullptr));
        Nosto60e->setText(QApplication::translate("MainWindow", "60 \342\202\254", nullptr));
        Nosto100e->setText(QApplication::translate("MainWindow", "100 \342\202\254", nullptr));
        Nosto200e->setText(QApplication::translate("MainWindow", "200 \342\202\254", nullptr));
        Nosto500e->setText(QApplication::translate("MainWindow", "500 \342\202\254", nullptr));
        Peruuta->setText(QApplication::translate("MainWindow", "PERUUTA", nullptr));
        label_7->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt;\">Rahat tulossa.</span></p><p align=\"center\"><span style=\" font-size:48pt;\">Paina jatka ja ota kortti.</span></p></body></html>", nullptr));
        Jatka->setText(QApplication::translate("MainWindow", "JATKA", nullptr));
        label_8->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt;\">Tilitapahtumat</span></p></body></html>", nullptr));
        label_9->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:26pt;\">Meik\303\244l\303\244inen Matti</span></p><p><span style=\" font-size:26pt;\">FI 22 0054 5493 0112</span></p><p><span style=\" font-size:26pt;\">Saldo: </span></p><p><span style=\" font-size:26pt;\">1.</span></p><p><span style=\" font-size:26pt;\">2.</span></p><p><span style=\" font-size:26pt;\">3.</span></p><p><span style=\" font-size:26pt;\">4.</span></p><p><span style=\" font-size:26pt;\">5.</span></p><p><span style=\" font-size:26pt;\">6.</span></p><p><span style=\" font-size:26pt;\">7.</span></p><p><span style=\" font-size:26pt;\">8.</span></p><p><span style=\" font-size:26pt;\">9.</span></p><p><span style=\" font-size:26pt;\">10.</span></p></body></html>", nullptr));
        Sulje->setText(QApplication::translate("MainWindow", "SULJE", nullptr));
        SeuraavaSivu->setText(QApplication::translate("MainWindow", "SEURAAVA SIVU", nullptr));
        label_11->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt;\">Saldo</span></p></body></html>", nullptr));
        label_12->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" font-size:26pt;\">Meik\303\244l\303\244inen Matti</span></p><p><span style=\" font-size:26pt;\">FI 22 0054 5493 0112</span></p><p><span style=\" font-size:26pt;\">Saldo: </span></p><p><span style=\" font-size:26pt;\">1.</span></p><p><span style=\" font-size:26pt;\">2.</span></p><p><span style=\" font-size:26pt;\">3.</span></p><p><span style=\" font-size:26pt;\">4.</span></p><p><span style=\" font-size:26pt;\">5.</span></p></body></html>", nullptr));
        Sulje_2->setText(QApplication::translate("MainWindow", "SULJE", nullptr));
        label_10->setText(QApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:68pt;\">Kiitos k\303\244ynnist\303\244.</span></p><p align=\"center\"><span style=\" font-size:68pt;\">Tervetuloa uudelleen!</span></p></body></html>", nullptr));
        banksimul->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" color:#5555ff;\">@BankSimul_700</span></p></body></html>", nullptr));
#ifndef QT_NO_WHATSTHIS
        KirjauduUlos_2->setWhatsThis(QApplication::translate("MainWindow", "<html><head/><body><p>background-color: rgb(33, 0, 70);</p><p>font: 36pt &quot;Ebrima&quot;; </p><p><br/></p></body></html>", nullptr));
#endif // QT_NO_WHATSTHIS
        KirjauduUlos_2->setText(QApplication::translate("MainWindow", "KIRJAUDU ULOS", nullptr));
#ifndef QT_NO_WHATSTHIS
        Paavalikko->setWhatsThis(QApplication::translate("MainWindow", "<html><head/><body><p>background-color: rgb(33, 0, 70);</p><p>font: 36pt &quot;Ebrima&quot;; </p><p><br/></p></body></html>", nullptr));
#endif // QT_NO_WHATSTHIS
        Paavalikko->setText(QApplication::translate("MainWindow", "P\303\204\303\204VALIKKO", nullptr));
#ifndef QT_NO_WHATSTHIS
        KirjauduSisaan->setWhatsThis(QApplication::translate("MainWindow", "<html><head/><body><p>background-color: rgb(33, 0, 70);</p><p>font: 36pt &quot;Ebrima&quot;; </p><p><br/></p></body></html>", nullptr));
#endif // QT_NO_WHATSTHIS
        KirjauduSisaan->setText(QApplication::translate("MainWindow", "KIRJAUDU SIS\303\204\303\204N", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
